# Generated by Django 6.0.3 on 2026-06-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_code',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='manager_name',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
